language: node_js
node_js:
  - '7'
  - '6'
after_script:
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
services: mongodb
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
